defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

paginate: 10
paginate_path: "/blog/page:num/"

title: ZhaoKang-Lab
subtitle: Bupt

left_side:
  background_image: "./assets/images/left-background.jpg"
#   background_color: "#000"
#   close_button_color: "#000"
#   text_color: "#000"

footer:
  copyright_text: "&copy; Moemoemaru"

# Side Menu Links
menu:
  - text: Profile
    link: /
    icon: ""

  - text: Openings
    link: /skills-and-offers
    icon: ""

  - text: Contact Me
    link: /contact
    icon: ""

  - text: Research Group
    link: /resume
    icon: ""

  - text: Publications
    link: /blog
    icon: ""

# Socialmedia Icons
social_icons:
#   - name: linkedin
#     link: https://www.linkedin.com/christianezeani
#     icon: fab fa-linkedin

  - name: github
    link: https://github.com/zhaokang-lab
    icon: fab fa-github-square

#   - name: facebook
#     link: https://www.facebook.com/christian.ezeani.cyb
#     icon: fab fa-facebook-square

#   - name: twitter
#     link: https://www.twitter.com/christianezeani
#     icon: fab fa-twitter


    
