defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

paginate: 10
paginate_path: "/blog/page:num/"

title: Moemoemaru
subtitle: Developer & Composer

left_side:
  background_image: "./assets/images/left-background.jpg"
  background_color: "#F26"
#   close_button_color: "#000"
#   text_color: "#000"

footer:
  copyright_text: "&copy; Moemoemaru"

# Side Menu Links
menu:
  - text: Profile
    link: /
    icon: ""

#   - text: Openings
#     link: /openings
#     icon: ""

  - text: Contact Me
    link: /contact
    icon: ""

#   - text: Research Group
#     link: /group
#     icon: ""

  - text: Music
    link: /music
    icon: ""
    
  - text: Publications
    link: /publications
    icon: ""

# Socialmedia Icons
social_icons:
#   - name: linkedin
#     link: https://www.linkedin.com/christianezeani
#     icon: fab fa-linkedin

  - name: github
    link: https://github.com/Moemoemaru
    icon: fab fa-github-square

  - name: youtube
    link: https://www.youtube.com/@moemoemaru3396
    icon: fab fa-youtube-square
    
#   - name: facebook
#     link: https://www.facebook.com/christian.ezeani.cyb
#     icon: fab fa-facebook-square

#   - name: twitter
#     link: https://www.twitter.com/christianezeani
#     icon: fab fa-twitter


    
